import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  ResponsiveContainer,
  BarChart, Bar, Cell,
  AreaChart, Area,
  XAxis, YAxis, CartesianGrid, Tooltip,
} from 'recharts';
import BuffiChat from './BuffiChat';
import { VIA_DATA_TOOLS } from '../../../frontend/src/services/agent';
import './ViaDashboard.css';

// Via dashboard — all of Via's visualization UI lives in this folder.
//
// Props (the plugin contract):
//   data  — output of Via's ParseLogic parse(files); null until that's built.
//   files — the raw uploaded CSV files, if the dashboard needs them directly.
//
// This dashboard ignores `files` and instead reads live VIA transit data from
// the MongoDB backend (GTFS collections imported by backend/import-gtfs.js).
// When no backend is reachable (e.g. the static GitHub Pages deploy) it falls
// back to JSON snapshots generated by backend/export-static-stats.js.
const API_BASE = process.env.REACT_APP_API_URL || 'http://localhost:5000';
const SNAPSHOT_BASE = `${process.env.PUBLIC_URL || ''}/data/via`;
const VIA_RED = '#CB2128';

async function getJson(path) {
  const res = await fetch(`${API_BASE}${path}`);
  if (!res.ok) {
    const body = await res.json().catch(() => ({}));
    throw new Error(body.message || `Request failed: ${res.status}`);
  }
  return res.json();
}

async function getSnapshotJson(file) {
  const res = await fetch(`${SNAPSHOT_BASE}/${file}`);
  if (!res.ok) throw new Error(`Snapshot request failed: ${res.status}`);
  return res.json();
}

// View state Buffi can change through the update_dashboard tool.
const MAX_ROUTES = 50;
const DEFAULT_VIEW = { routeLimit: 10, highlightRoute: null, hourMin: 0, hourMax: 23 };
const DIM_GREY = '#e2e2e6';

const CHAT_SYSTEM_PROMPT = [
  'You are Buffi, a data assistant embedded in the VIA Metropolitan Transit dashboard.',
  'Query VIA GTFS schedule data with get_stats, get_trips_per_route, and get_departures_by_hour.',
  'Change what the dashboard charts display with update_dashboard: how many of the busiest',
  'routes are charted, which route is highlighted, and the hour range of the departures chart.',
  'When the user asks to show, focus on, filter, highlight, or reset the view, call update_dashboard.',
  'Call tools to look at real data before answering; never invent values.',
  'Use Markdown. Be concise.',
].join(' ');

const UPDATE_DASHBOARD_TOOL = {
  type: 'function',
  function: {
    name: 'update_dashboard',
    description: 'Change what the VIA dashboard charts display. Omitted fields keep their current value.',
    parameters: {
      type: 'object',
      properties: {
        top_routes_limit: {
          type: 'integer',
          description: `How many of the busiest routes to chart (1-${MAX_ROUTES}).`,
        },
        highlight_route_short_name: {
          type: 'string',
          description: 'Route short name (e.g. "100") to highlight in the routes chart; other bars are dimmed. Empty string clears the highlight.',
        },
        hour_min: { type: 'integer', description: 'First hour (0-23) shown in the departures-by-hour chart.' },
        hour_max: { type: 'integer', description: 'Last hour (0-23) shown in the departures-by-hour chart.' },
        reset: { type: 'boolean', description: 'Reset the dashboard to its default view.' },
      },
    },
  },
};

const clampInt = (v, lo, hi, fallback) => {
  const n = Number.isFinite(v) ? Math.round(v) : fallback;
  return Math.max(lo, Math.min(hi, n));
};

const fmt = (n) => (typeof n === 'number' ? n.toLocaleString() : '—');

// GTFS dates are YYYYMMDD strings.
const fmtFeedDate = (s) =>
  s && s.length === 8 ? `${s.slice(4, 6)}/${s.slice(6, 8)}/${s.slice(0, 4)}` : s || '';

const hourLabel = (h) => {
  if (h === 0) return '12 AM';
  if (h === 12) return '12 PM';
  return h < 12 ? `${h} AM` : `${h - 12} PM`;
};

function RouteTooltip({ active, payload }) {
  if (!active || !payload || !payload.length) return null;
  const r = payload[0].payload;
  return (
    <div className="via-tooltip">
      <div className="via-tooltip-title">{r.route_short_name} — {r.route_long_name}</div>
      <div>{fmt(r.trips)} scheduled trips</div>
    </div>
  );
}

function HourTooltip({ active, payload }) {
  if (!active || !payload || !payload.length) return null;
  const d = payload[0].payload;
  return (
    <div className="via-tooltip">
      <div className="via-tooltip-title">{hourLabel(d.hour)}</div>
      <div>{fmt(d.departures)} departures</div>
    </div>
  );
}

export default function ViaDashboard({ data = null, files = [] }) {
  const [stats, setStats] = useState(null);
  const [topRoutes, setTopRoutes] = useState([]);
  const [byHour, setByHour] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [isSnapshot, setIsSnapshot] = useState(false);
  const [view, setView] = useState(DEFAULT_VIEW);
  const viewRef = useRef(DEFAULT_VIEW);
  const routesRef = useRef([]);

  useEffect(() => {
    let cancelled = false;
    Promise.all([
      getJson('/api/stats'),
      getJson(`/api/stats/trips-per-route?limit=${MAX_ROUTES}`),
      getJson('/api/stats/departures-by-hour'),
    ])
      .catch(() =>
        Promise.all([
          getSnapshotJson('stats.json'),
          getSnapshotJson('trips-per-route.json'),
          getSnapshotJson('departures-by-hour.json'),
        ]).then((results) => {
          if (!cancelled) setIsSnapshot(true);
          return results;
        })
      )
      .then(([s, routes, hours]) => {
        if (cancelled) return;
        setStats(s);
        setTopRoutes(routes);
        routesRef.current = routes;
        setByHour(hours);
      })
      .catch((err) => { if (!cancelled) setError(err.message); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, []);

  // Executes Buffi's update_dashboard tool calls. Uses refs (not state) so the
  // closure stays valid for the whole multi-round agent loop.
  const applyDashboardUpdate = useCallback((args = {}) => {
    const prev = viewRef.current;
    let next;
    if (args.reset) {
      next = { ...DEFAULT_VIEW };
    } else {
      next = {
        routeLimit: clampInt(args.top_routes_limit, 1, MAX_ROUTES, prev.routeLimit),
        highlightRoute:
          args.highlight_route_short_name === undefined
            ? prev.highlightRoute
            : String(args.highlight_route_short_name).trim() || null,
        hourMin: clampInt(args.hour_min, 0, 23, prev.hourMin),
        hourMax: clampInt(args.hour_max, 0, 23, prev.hourMax),
      };
      if (next.hourMin > next.hourMax) {
        [next.hourMin, next.hourMax] = [next.hourMax, next.hourMin];
      }
    }

    const result = { ok: true };
    if (next.highlightRoute) {
      const idx = routesRef.current.findIndex((r) => r.route_short_name === next.highlightRoute);
      if (idx === -1) {
        result.warning = `Route "${next.highlightRoute}" is not among the ${routesRef.current.length} busiest routes, so nothing is highlighted.`;
        result.available_route_short_names = routesRef.current.map((r) => r.route_short_name);
      } else if (idx >= next.routeLimit) {
        // Widen the chart so the highlighted route is actually visible.
        next.routeLimit = idx + 1;
      }
    }

    viewRef.current = next;
    setView(next);
    result.view = next;
    return result;
  }, []);

  const chatTools = useMemo(
    () => [...VIA_DATA_TOOLS, { definition: UPDATE_DASHBOARD_TOOL, run: applyDashboardUpdate }],
    [applyDashboardUpdate],
  );

  if (loading) {
    return (
      <div className="via-dashboard">
        <div className="via-dashboard-placeholder">Loading VIA transit data…</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="via-dashboard">
        <div className="via-dashboard-placeholder">
          Couldn&rsquo;t reach the VIA database — {error}
        </div>
      </div>
    );
  }

  const shownRoutes = topRoutes.slice(0, view.routeLimit);
  const shownHours = byHour.filter((d) => d.hour >= view.hourMin && d.hour <= view.hourMax);
  const fullDay = view.hourMin === 0 && view.hourMax === 23;

  const kpis = [
    { label: 'Bus Routes', value: stats.routes },
    { label: 'Stops', value: stats.stops },
    { label: 'Scheduled Trips', value: stats.trips },
    { label: 'Stop Departures', value: stats.stop_times },
    { label: 'Uploaded Sources', value: stats.sources },
  ];

  return (
    <div className="via-dash">
      <div className="via-dash-header">
        <h2 className="via-dash-title">VIA Metropolitan Transit</h2>
        {stats.feed && (
          <span className="via-dash-feed">
            Feed {stats.feed.feed_version} · valid {fmtFeedDate(stats.feed.feed_start_date)} – {fmtFeedDate(stats.feed.feed_end_date)}{isSnapshot && ' · static snapshot'}
          </span>
        )}
      </div>

      <div className="via-kpi-grid">
        {kpis.map((k) => (
          <div key={k.label} className="via-kpi-card">
            <span className="via-kpi-value">{fmt(k.value)}</span>
            <span className="via-kpi-label">{k.label}</span>
          </div>
        ))}
      </div>

      <div className="via-chart-grid">
        <div className="via-chart-card">
          <h3 className="via-chart-title">
            Busiest Routes by Scheduled Trips (top {view.routeLimit})
            {view.highlightRoute && ` · highlighting ${view.highlightRoute}`}
          </h3>
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={shownRoutes} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" vertical={false} />
              <XAxis dataKey="route_short_name" tick={{ fontSize: 12 }} />
              <YAxis tick={{ fontSize: 12 }} width={48} />
              <Tooltip content={<RouteTooltip />} />
              <Bar dataKey="trips" radius={[4, 4, 0, 0]}>
                {shownRoutes.map((r) => (
                  <Cell
                    key={r.route_id}
                    fill={
                      view.highlightRoute && r.route_short_name !== view.highlightRoute
                        ? DIM_GREY
                        : r.route_color ? `#${r.route_color}` : VIA_RED
                    }
                  />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>

        <div className="via-chart-card">
          <h3 className="via-chart-title">
            System Departures by Hour
            {!fullDay && ` (${hourLabel(view.hourMin)} – ${hourLabel(view.hourMax)})`}
          </h3>
          <ResponsiveContainer width="100%" height={260}>
            <AreaChart data={shownHours} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" vertical={false} />
              <XAxis
                dataKey="hour"
                tickFormatter={hourLabel}
                tick={{ fontSize: 12 }}
                interval={shownHours.length > 12 ? 3 : 0}
              />
              <YAxis tick={{ fontSize: 12 }} width={56} />
              <Tooltip content={<HourTooltip />} />
              <Area
                type="monotone"
                dataKey="departures"
                stroke={VIA_RED}
                fill={VIA_RED}
                fillOpacity={0.15}
                strokeWidth={2}
              />
            </AreaChart>
          </ResponsiveContainer>
        </div>
      </div>

      <BuffiChat
        systemPrompt={CHAT_SYSTEM_PROMPT}
        tools={chatTools}
        suggestion="highlight the busiest route and show only morning departures"
      />
    </div>
  );
}
